[package]
authors = ["David Peter <mail@david-peter.de>"]
categories = ["command-line-utilities"]
homepage = "https://github.com/sharkdp/dup"
name = "dup"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/sharkdp/dup"
version = "0.1.0"

[dependencies]
ignore = "0.4.3"
num_cpus = "1.0"
humansize = "1.1"

[profile.release]
lto = true
codegen-units = 1
