[package]
authors = ["David Peter <mail@david-peter.de>"]
categories = ["command-line-utilities"]
description = "A minimal, fast alternative to 'du -sh'."
homepage = "https://github.com/sharkdp/dup"
license = "MIT/Apache-2.0"
name = "dup"
readme = "README.md"
repository = "https://github.com/sharkdp/dup"
version = "0.1.0"

[dependencies]
ignore = "0.4.3"
num_cpus = "1.0"
humansize = "1.1"

[profile.release]
lto = true
codegen-units = 1
